### ISSUE TITLE
Tower of Hera Issue

### ISSUE THREAD

**Issue by Jaylow7** [Loogaroo1/ALTTP-RandoTracker#7]
In a run I did today (keysanity mode, but this has also happened recently in non keysanity) the tracker would not let me mark Hera as completed. 

I had logical access (mirror + power glove), the small key, and the big key. 
I was not actually able to mark it complete until very late in the seed when I finally found Hookshot at the top of Ganon's Tower.

**Comment by Loogaroo1** [comment]
Sorry I didn't see this sooner.

I'm in the process of rewriting all of the logic (to add Enemizer functionality) with a two-phase test to check separately for the dungeon being open and the boss being vulnerable. Previous iterations would check for all items at once, which may have resulted in the error here. (Probably missed the mirror in the logic and would only open up Hera if you had the Hammer and Hookshot to come around via the east.)

FYI, this didn't cause the issue here, but keep in mind that the logic also checks to make sure that you have the means to defeat the boss in that dungeon. Obviously this means the Ice Rod for Trinexx, but it also means either a sword or a hammer for most other bosses. Even if you can reach the boss room, the boss won't unlock unless you can beat it.

**Comment by Loogaroo1** [comment]
Logic issue has been corrected in 1.3.
